#!/usr/bin/env sh
set -eu

make check_fix

if command -v lint-ifchange >/dev/null 2>&1; then
  git diff --cached --no-ext-diff --relative | lint-ifchange
else
  git diff --cached --no-ext-diff --relative | cargo run --quiet --release --
fi
